linuxdeepin/lastore-daemon

src/internal/system/common.go, src/lastore-daemon/manager.go
新开发了内测源相关的功能，新增了/etc/apt/sources.list.d/deepin-unstable-source.list的文件，社区版内测源非第三方仓库，因此将该仓库地址加入到默认的白名单内
=> feat: add DeepinTestSource

src/lastore-daemon/manager.go
修改触发次数限制的默认值
Log: 修复watchUpdateInfo.path触发频率过高导致报错问题
Bug: https://pms.uniontech.com/bug-view-159517.html
Bug: https://pms.uniontech.com/bug-view-156721.html
Influence: 报错日志
=> fix: 修复watchUpdateInfo.path触发频率过高导致报错问题

src/internal/system/common.go
控制中心无法接收内测源更新,移除后内测源默认走第三方仓库更新
=> fix: 控制中心无法接收内测源更新,移除相关提交

src/lastore-daemon/manager.go
由于上报数据时使用的是下载任务的job，导致无法将安装失败的日志上报
Log: 修复上报更新平台信息无失败日志的问题
Bug: https://pms.uniontech.com/bug-view-168719.html
Influence: 上报数据
=> fix: 修复上报更新平台信息无失败日志的问题

src/internal/system/common.go
变量使用错误导致内测源被识别为第三方仓库
Log: 修复内测源被识别为第三方仓库
Bug: https://pms.uniontech.com/bug-view-172585.html
Influence: 系统更新 内测源更新
=> fix: 修复内测源被识别为第三方仓库

.reuse/dep5, .tx/deepin.conf, debian/changelog
发布6.1.0.0版本,用于集成deepin v23
Log:
=> chore: Release 6.1.0.0 version

debian/changelog
发布6.2.0版本,用于和控制中心的内测渠道一起提测
Log:
=> chore: Release 6.2.0 version

src/lastore-daemon/manager.go
=> chore: add legacy AM daemon compat service to allowlist

debian/changelog, lib/systemd/system/lastore-daemon.service
防止进程运行时，非主进程向 /run/systemd/notify 发送信号，导致 lastore-daemon 未退出，被 systemd SIGKILL 掉
Ref: https://github.com/linuxdeepin/developer-center/issues/8532
=> fix: Set NotifyAccess to main in lastore-daemon.service

src/lastore-daemon/common.go
将其加入允许安装的列表
Bug: https://pms.uniontech.com/bug-view-273975.html
Log: 修复旧版控制中心无法加入内测的问题
=> fix: 修复旧版控制中心无法加入内测的问题

etc/apt/apt.conf.d/99lastore.conf, etc/apt/apt.conf.d/99mirrors.conf, src/lastore-smartmirror-daemon/smartmirror.go, var/lib/lastore/mirrors.json
cdn服务器地址不正确，导致匹配不到
Log: 解决智能镜像源配置不生效的问题
pms: BUG-302185
=> fix: 解决智能镜像源配置不生效的问题

src/lastore-daemon/exported_methods_auto.go, src/lastore-daemon/manager_ifc.go
由于之前去掉了一些暂时没有用到的接口，但是这些失败的服务调用其中的一个接口，现在将这个接口添加回去
Log: 解决系统启动时lastore的自启动的一些服务运行失败的问题
pms: BUG-303841
=> fix: 解决系统启动时lastore的自启动的一些服务运行失败的问题

debian/changelog
=> chore: bump version to 6.2.16

src/lastore-daemon/manager_upgrade.go
Ensure the correct handling of script ignore error options under specific conditions.
pms: BUG-320601
=> fix: check if dpkg supports --script-ignore-error

src/lastore-daemon/dbusutil.go, src/lastore-daemon/manager.go, src/lastore-daemon/manager_update.go
After enabling automatic restore, updates are invalid, so checking for updates is directly prohibited
pms: TASK-378055
=> feat: Prohibit checking for updates when automatic restore is enabled

debian/changelog
=> chore: bump version to 6.2.21

debian/changelog
=> chore: bump version to 6.2.22

src/lastore-daemon/manager_ifc.go, src/lastore-daemon/manager_upgrade.go
1. Modified ConfirmRollback to handle rollback synchronously instead of in goroutine
2. Added Reboot field to ostreeRollbackData struct to track reboot requirement
3. Implemented osTreeNeedRebootAfterRollback to properly determine reboot need
4. Updated osTreeParseRollbackData to return additional field information
5. Added slices package import for field checking
The changes improve rollback reliability by:
1. Making rollback operations synchronous to properly handle errors
2. Adding explicit reboot tracking instead of relying on auto-rollback status
3. Maintaining backward compatibility with older ostree versions
4. Providing better field-level data access from ostree responses
fix: 改进回滚处理逻辑
1. 修改 ConfirmRollback 以同步方式处理回滚而非使用 goroutine
2. 在 ostreeRollbackData 结构体中添加 Reboot 字段以跟踪重启需求
3. …
=> fix: improve rollback handling logic

debian/changelog
=> chore: bump version to 6.2.26

lib/systemd/system/lastore-abort-auto-download.service, lib/systemd/system/lastore-auto-download.service, src/lastore-daemon/common.go, src/lastore-daemon/common_test.go, src/lastore-daemon/job.go, src/lastore-daemon/main.go, src/lastore-daemon/manager.go, src/lastore-daemon/manager_download.go, src/lastore-daemon/manager_idle.go, src/lastore-daemon/manager_ifc.go, src/lastore-daemon/manager_unit.go, src/lastore-daemon/manager_update.go, src/lastore-daemon/updater.go, src/lastore-daemon/updater_ifc.go
* Use a persistent timer file instead of a transient one.
* Differentiate between automatic and manually triggered
downloads; only stop automatic downloads when idle-time
downloading finishes.
* 11 minutes after startup, check if the current time
falls within the idle-time downloading window, and if
so, start automatic downloading.
* 使用永久 timer 文件替代 transient 的 timer。
* 区分自动下载和手动触发下载，只在闲时下载结束时停止自动下载。
* 开机后11分钟，检查现在是否处于闲时下载时间区间内，如果处于则开始自动下载。
Log: 修复闲时下载相关问题
Bug: Bug-317329, Bug-317345, Bug-321655
=> fix: Issues related to idle-time downloading

src/lastore-daemon/manager_upgrade.go
- Set UpdateStatus to WaitRunUpgrade when backup job starts running
- Reset UpdateStatus to CanUpgrade when backup job fails
Bug: https://pms.uniontech.com/bug-view-327939.html
=> fix: hide power menu update buttons during backup process

src/internal/updateplatform/message_report.go, src/lastore-daemon/manager.go, src/lastore-daemon/manager_check.go, src/lastore-daemon/manager_download.go, src/lastore-daemon/manager_update.go, src/lastore-daemon/manager_upgrade.go
send json string to update platform
Task: https://pms.uniontech.com/task-view-380017.html
=> feat: Modify the format of the data sent to the update platform

usr/bin/lastore-update-tools
Add the lastore-update-tools shell script, which always executes
successfully.
pms: BUG-336013
=> fix: Upgrade failed due to missing lastore-update-tools executable
