linuxdeepin/lastore-daemon

src/internal/system/common.go

if the file update_infos.json not exist
https://github.com/linuxdeepin/internal-discussion/issues/1341

fix: SystemUpgradeInfo return error

---

src/lastore-daemon/job.go
src/lastore-daemon/main.go
src/lastore-daemon/manager.go
src/lastore-daemon/start_job.go

https://github.com/linuxdeepin/internal-discussion/issues/1496

fix: can not get upgradeable packages after update source job is end

---

var/lib/lastore/mirrors.json

Fixes https://github.com/linuxdeepin/developer-center/issues/2007

fix: remove outdated mirrors

---

src/lastore-daemon/main.go
src/lastore-daemon/manager.go
src/lastore-daemon/systeminfo_utils.go
src/lastore-daemon/systeminfo_utils_test.go

新增oemid和Machine model上报更新平台
Log: 新增oemid和Machine model上报更新平台
Task: https://pms.uniontech.com/task-view-175027.html
Influence: apt上报

feat: 新增oemid和Machine model上报更新平台

---

src/lastore-daemon/manager.go

导出机器码供其他模块读取
Log: 导出机器码
Task: https://pms.uniontech.com/task-view-174017.html
Influence: 无
Change-Id: Ie825295a6d62c172d9999cf9b023c2249fd248ba

feat: 导出机器码

---

src/lastore-daemon/main.go

oid写成了ois，需要修正
Log: 修复apt上报字段key错误问题
Bug: https://pms.uniontech.com/bug-view-152909.html
Influence: apt 上报数据

fix: 修复apt上报字段key错误问题

---

src/lastore-daemon/manager.go

删除partial文件夹修改为移除文件夹内容
Log: 删除partial文件夹修改为移除文件夹内容
Bug: https://pms.uniontech.com/bug-view-154249.html
Influence: 检查更新
(cherry picked from commit d88170e4de57da29dee7ca85e8e478594a4b76ec)

fix: 删除partial文件夹修改为移除文件夹内容

---

src/lastore-daemon/manager.go

存在下载或者安装时,不再调用检查更新
Log: 修复下载或安装时偶然触发检查更新问题
Bug: https://pms.uniontech.com/bug-view-155447.html
Influence: 检查更新

fix: 修复下载或安装时偶然触发检查更新问题

---

src/internal/system/common.go
src/internal/system/common_test.go
src/lastore-daemon/job_manager.go
src/lastore-tools/upgradable.go

创建/var/lib/lastore/SystemSource.d的目录将内测源以及系统源软连接到这里 使用指定目录的形式进行系统升级
Log: 添加内测源到默认的系统更新
Influence: 控制中心更新 系统更新 内测更新

feat: 添加内测源到默认的系统更新

---

src/internal/system/common.go

将hwe仓库归类为系统仓库
Log: 增加hwe仓库
Task: https://pms.uniontech.com/task-view-212753.html
Influence: hwe仓库判断

feat: 增加hwe仓库

---

src/lastore-daemon/manager.go
src/lastore-daemon/systeminfo_utils.go

原因:更新失败时，可能os-version文件已经是最新的了，所以token文件的内容被更新了。
方案:更新失败时，将更新前系统版本进行保存，并更新token文件。
Log: 修复更新失败后再检查更新时，token中版本信息可能错误的问题
Bug: https://pms.uniontech.com/bug-view-169873.html
Influence: 更新平台上报数据

fix: 修复更新失败后再检查更新时，token中版本信息可能错误的问题

---

src/lastore-daemon/systeminfo_utils.go

修改oemid获取方式
task: https://pms.uniontech.com/task-view-218349.html
Log: 修改oemid获取方式
Influence: apt上报字段

feat: 修改oemid获取方式

---

.obs/workflows.yml

obs build use beige develop repo
Log:

chore: add obs workflow

---

.obs/workflows.yml

lastore-daemon应该在obs的dde项目中
Log:

chore: move obs project

---

debian/changelog
debian/rules

fix: upgrade fail

---

src/lastore-daemon/manager.go

dde-applciation-manager ==> dde-launcher
am 重构之后不再做卸载的事，launcher 自己做

fix: launcher uninstall app failed

---

lib/systemd/system/lastore-daemon.service
lib/systemd/system/lastore-smartmirror-daemon.service
src/lastore-smartmirror-daemon/smartmirror.go
usr/share/dbus-1/system-services/org.deepin.dde.Lastore1.Smartmirror.service
usr/share/dbus-1/system-services/org.deepin.dde.Lastore1.service
usr/share/dbus-1/system.d/org.deepin.dde.Lastore1.Smartmirror.conf
usr/share/polkit-1/actions/org.deepin.dde.Lastore1.policy
usr/share/polkit-1/actions/org.deepin.dde.Lastore1Smartmirror.policy

chore: 安全加固

---

src/internal/dstore/dstore.go

chore: fix a crash

---

usr/share/dbus-1/system-services/com.deepin.lastore.Smartmirror.service
usr/share/dbus-1/system-services/com.deepin.lastore.service

chore: remove unnecessary dbus services

---

debian/changelog

chore: bump to 6.2.6

---

etc/apt/apt.conf.d/99lastore.conf
lib/systemd/system/lastore-smartmirror-daemon.service
src/lastore-daemon/manager_upgrade.go
src/lastore-smartmirror-daemon/smartmirror.go
var/lib/lastore/mirrors.json

ostree deploy
Log: ostree deploy
pms: TASK-362299

feat: ostree deploy

---

debian/changelog

chore: bump to 6.2.8

---

var/lib/lastore/mirrors.json

更新智能镜像源地址
Log: 更新智能镜像源地址
pms: BUG-303841

fix: 更新智能镜像源地址

---

lib/systemd/system/lastore-daemon.service

lastore-daemon开机自启
Log: lastore-daemon开机自启
pms:

fix: lastore-daemon开机自启

---

debian/changelog

chore: bump to 6.2.9

---

src/lastore-daemon/manager_upgrade.go

更新前后调用ostree的backup和deploy
Log: 更新前后调用ostree的backup和deploy
pms:

feat: 更新前后调用ostree的backup和deploy

---

debian/changelog

chore: bump to 6.2.10

---

src/lastore-daemon/manager_upgrade.go

feat: 适配磐石系统备份方案

---

debian/changelog

chore: bump to 6.2.11

---

debian/control
lib/systemd/system/lastore-after-upgrade-check.service
lib/systemd/system/lastore-daemon.service
src/internal/system/apt/apt.go
src/internal/system/apt/proxy.go
src/internal/system/dut/common.go
src/internal/system/dut/dut.go
src/internal/system/dut/proxy.go
src/internal/system/system.go
src/internal/updateplatform/message_report.go
src/lastore-daemon/common.go
src/lastore-daemon/exported_methods_auto.go
src/lastore-daemon/job_manager.go
src/lastore-daemon/manager.go
src/lastore-daemon/manager_check.go
src/lastore-daemon/manager_ifc.go
src/lastore-daemon/manager_update.go
src/lastore-daemon/manager_upgrade.go
src/lastore-daemon/start_job.go
src/lastore-daemon/updater.go
src/lastore-daemon/updater_ifc.go
usr/share/dbus-1/interfaces/org.deepin.dde.Lastore1.Job.xml
usr/share/dbus-1/interfaces/org.deepin.dde.Lastore1.xml
usr/share/dsg/configs/org.deepin.dde.lastore/org.deepin.dde.lastore.json
usr/share/lightdm/lightdm.conf.d/90-deepin-upgrade.conf
var/lib/lastore/scripts/gen_upgrade_check_config.sh
var/lib/lastore/scripts/upgrade_check.sh

更新方案变更，添加dut更新
Log: 更新方案变更，添加dut更新
pms: TASK-362299

feat: 更新方案变更，添加dut更新

---

debian/changelog

chore: bump to 6.2.12

---

src/internal/system/apt/proxy.go
src/internal/system/dut/common.go
src/internal/system/dut/dut.go
src/internal/system/dut/proxy.go
src/internal/updateplatform/message_report.go
src/lastore-apt-clean/main.go
src/lastore-daemon/exported_methods_auto.go
src/lastore-daemon/main.go
src/lastore-daemon/manager_check.go
src/lastore-daemon/manager_ifc.go
src/lastore-daemon/manager_upgrade.go
usr/share/dbus-1/interfaces/org.deepin.dde.Lastore1.xml
usr/share/dsg/configs/org.deepin.dde.lastore/org.deepin.dde.lastore.json

支持更新平台更新和ostree备份
Log: 支持更新平台更新和ostree备份

feat: 支持更新平台更新和ostree备份

---

src/internal/system/dut/dut.go

适配系统检查工具，meta支持空数据
Log: 适配系统检查工具，meta支持空数据

feat: 适配系统检查工具，meta支持空数据

---

src/lastore-daemon/manager.go

fix: 删除旧的原子更新方案

---

debian/changelog
usr/share/dsg/configs/org.deepin.dde.lastore/org.deepin.dde.lastore.json

fix: 默认走本地更新

---

src/lastore-daemon/manager_upgrade.go

解决安装时没有阻塞重启/关机的问题
Log: 解决安装时没有阻塞重启/关机的问题
pms: BUG-313841

fix: 解决安装时没有阻塞重启/关机的问题

---

src/internal/config/config.go
src/internal/updateplatform/message_report.go
usr/share/dsg/configs/org.deepin.dde.lastore/org.deepin.dde.lastore.json

更新平台仓库的组件可配置
Log: 更新平台仓库的组件可配置
pms: BUG-313777

fix: 更新平台仓库的组件可配置

---

.tx/transifex.yaml

chore: add transifex config file

---

src/internal/system/apt/proxy.go
src/internal/system/command.go
src/internal/system/system_apt.go
src/lastore-daemon/manager_upgrade.go
src/lastore-tools/upgradable.go

解决升级过程中，磐石系统remount次数过多的问题
Log: 解决升级过程中，磐石系统remount次数过多的问题

fix: 解决升级过程中，磐石系统remount次数过多的问题

---

debian/changelog

chore: bump version to 6.2.20

---

src/lastore-daemon/manager_ifc.go
src/lastore-daemon/manager_upgrade.go

When automatic rollback is enabled, no reboot
pms: TASK-377783

feat: adapt to automatic rollback

---

debian/changelog

chore: bump version to 6.2.23

---

debian/changelog

chore: bump version to 6.2.24

---

src/internal/system/dut/dut.go
src/internal/system/dut/proxy.go
src/internal/updateplatform/message_report.go
src/lastore-update-tools/controller/check/check.go
src/lastore-update-tools/controller/check/check_test.go

Execute custom check scripts, which can be used for pre-update checks, update checks, and post-update checks.
Task: https://pms.uniontech.com/task-view-380015.html
Influence: update check

feat: Added the ability to execute check scripts

---

debian/changelog

chore: bump version to 6.2.31
